codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        # Basic project coverage settings
        target: 80%
        threshold: 2%
        if_not_found: failure
        if_ci_failed: error
    patch:
      default:
        # PR patch coverage settings
        target: 80%
        threshold: 2%
        if_not_found: failure
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
