codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "0...100"
  
  status:
    project:
      default:
        # Realistic project coverage settings for microservice
        target: 30%
        threshold: 5%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        # PR patch coverage settings - new code should be well tested
        target: 60%
        threshold: 10%
        if_not_found: success
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*_mock.go"
  - "**/mocks/**"
  - "cmd/companies/main.go"
