name: Unit Tests and Coverage

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download

    - name: Run migrations
      run: |
        go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
        migrate -database "postgres://postgres:postgres@localhost:5432/testdb?sslmode=disable" -path migrations up
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb?sslmode=disable

    - name: Run unit tests with coverage
      run: |
        # Run only unit tests, skip integration tests
        go test -v -race -coverprofile=coverage.out -covermode=atomic \
          ./internal/auth/... \
          ./internal/config/... \
          ./internal/http/... \
          ./internal/kafka/... \
          ./internal/middlewares/... \
          ./internal/models/... \
          ./internal/repository/... \
          ./internal/service/...
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: testdb
        DB_SSL_MODE: disable
        KAFKA_ADDR: localhost:9092
        KAFKA_TOPIC: companies-mutations
        JWT_KEY: test-secret-key
        HTTP_PORT: 8080
        LOG_LEVEL: debug

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.out
        flags: unittests
        name: codecov-companies
        fail_ci_if_error: false
        verbose: true
